from __future__ import annotations

import json
import zipfile
from dataclasses import asdict
from pathlib import Path

from cadcore.models import ConversionReport


def write_delivery_readme(report: ConversionReport, readme_path: Path) -> None:
    findings = "\n".join(f"- {item}" for item in report.findings) or "- None"
    readme_path.write_text(
        f"""# PDF-to-CAD Delivery

Status: `{report.status}`

Recommended CAD file: `{Path(report.recommended_cad_file).name}`
Preview PDF: `{Path(report.preview_pdf).name}`
Quality report: `quality_report.json`

## Summary

- Source type: `{report.source_type}`
- Pages: {report.page_count}
- CAD entities: {report.entity_count}
- Extracted text entities: {report.text_count}
- CJK text entities: {report.cjk_text_count}
- OCR-recovered text entities: {report.ocr_text_count}
- Unresolved garbled text entities: {report.garbled_text_count}
- Dimension-like text entities: {report.dimension_text_count}
- Title-block-like text entities: {report.title_text_count}

## Review Findings

{findings}

## Notes

This package is generated by the standalone OpenClaw PDF-to-CAD skill. For scanned or mixed PDFs, treat the DXF as a review candidate and verify geometry and dimensions before manufacturing use.
""",
        encoding="utf-8",
    )


def zip_dir(directory: Path, zip_path: Path) -> None:
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for file_path in sorted(directory.rglob("*")):
            if file_path == zip_path or not file_path.is_file():
                continue
            zf.write(file_path, file_path.relative_to(directory))


def write_quality_report(report: ConversionReport, report_path: Path) -> None:
    report_path.write_text(
        json.dumps({**asdict(report), "quality_report": str(report_path)}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
